#pragma once

#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION "0.3.1"
#endif

#ifndef HARDWARE_REVISION
#define HARDWARE_REVISION "JC8048W550C-R1"
#endif

#ifndef PROTOCOL_VERSION
#define PROTOCOL_VERSION 4
#endif

#define FIRMWARE_BUILD_DATE __DATE__
#define FIRMWARE_BUILD_TIME __TIME__
